---

- name: Install nginx
  yum:
    pkg: nginx
  notify:
    - restart nginx

- name: Replace default nginx.conf
  copy:
    src:  files/nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: Check if galaxy.conf exist
  ansible.builtin.stat:
    path: /etc/nginx/conf.d/galaxy.conf    
  register: st

- name: Report if galaxy conf exist
  ansible.builtin.debug:
    msg: "The file exists"
  when: st.stat.exists

- name: Report if galaxy conf missing
  ansible.builtin.debug:
    msg: "The file does not exists"
  when: not st.stat.exists

- name: Create galaxy conf from template https
  template:
    src: templates/galaxy.j2
    dest: /etc/nginx/conf.d/galaxy.conf
    backup: yes
  when:  not st.stat.exists and use_ssl
  notify:
    - reload nginx

- name: Create redirect conf from template https
  template:
    src: templates/redirect-ssl.j2
    dest: /etc/nginx/conf.d/redirect_ssl.conf
    backup: yes
  when:  use_ssl
  notify:
    - reload nginx

#
# - name: Create galaxy conf from template https
#   template:
#     src: templates/galaxy_ssl.conf.j2
#     dest: /etc/nginx/conf.d/galaxy.conf
#     backup: yes
#   when:  not st.stat.exists and use_ssl
#   notify:
#     - reload nginx
#
# - name: Create galaxy conf from template http
#   template:
#     src: templates/galaxy.conf.j2
#     dest: /etc/nginx/conf.d/galaxy.conf
#     backup: yes
#   when:  not st.stat.exists and not use_ssl
#   notify:
#     - reload nginx

- name: Setting up Nginx to forward traffic
  command: setsebool -P httpd_can_network_connect 1
  notify:
    - restart nginx
